feat: driver 위치 저장
QRTaxi/QRTaxi_Server pull request #12
Opened 2023-08-04 11:06 UTC by ChoiYoo

### 작업한 내용
- 기사님 위치 저장

### 논의할 내용
- 레디스 연결 부분이 중복되어서 util로 따로 뺐습니다.
- 3분마다 클라이언트로부터 기사님 위치 정보를 받는거라 위치 저장 성공시 status 200만 반환하도록 설정했습니다.
- 그 외 이상한 부분 있으면 말씀해주세요!

- 그리고 이 pr가 논외로 현재 기사님이 메인 페이지, 즉 콜을 받는 페이지에 접속하면 소켓이 연결되도록 설정했습니다.(이 부분은 아직 pr에 안 올렸습니다) 저번에 말씀해주신대로, 그룹 생성하지 않고 가까운 기사님 id를 모두에게 보내려고 하는데 어떠신가요? 
사실 기사님 수 생각하지 않고 진행한다면 기사님 id별로 그룹생성하는 것도 나쁘지 않을 거 같아서.. 전자의 경우, 클라이언트 쪽이 복잡해진다고 해서 어떻게 하면 좋을지 두분에게 의견을 물어보고 싶습니다!

### 추후 진행할 내용
- 논의 내용 바탕으로 가까운 기사님에게 콜 보내기

2023-08-04 13:40 UTC, leehjhjhj requested changes
코드 짜시느라 고생하셨어요! util에 redis uitl 넣는거 👍 저도 코드 수정해야겠어요. 저거 status code 관련된 것만 보시면 될 것 같아요!

2023-08-04 13:40 UTC, leehjhjhj commented on driver/views/driver_location_view.py
> +            elif response['status'] == 'OK':
OK일 때도 마찬가지로 statusCode를 보내줘야 될 것 같아요!

2023-08-04 13:54 UTC, kimjeongsoo20190147 commented
확인했습니다! 저도 mypage 관련해서 얼른 올릴게요!!

2023-08-04 14:04 UTC, leehjhjhj commented
+) 저 소켓 연결 관해서는,, 일단은 전체 보내는 것도 나쁘지 않을 것 같아요. 그리고 소켓 연결을 백에서 설정해주는 거였나요??? 프론트에서 객체생성해서 연결하는거 아니었나요 ?_?

2023-08-04 14:37 UTC, ChoiYoo commented
> +) 저 소켓 연결 관해서는,, 일단은 전체 보내는 것도 나쁘지 않을 것 같아요. 그리고 소켓 연결을 백에서 설정해주는 거였나요??? 프론트에서 객체생성해서 연결하는거 아니었나요 ?_?

아 그 세팅을 했다는 말이였습니다..ㅎㅎ 그러면 일단 전체 보내는걸로 염두에 두고 개발진행하겠습니다!!

2023-08-05 00:11 UTC, leehjhjhj approved these changes
고생하셨어요!! 근데 저렇게 에러코드 뱉으려면 raise Exception()은 쓸 수 없겠군요.. 쩝 저것도 아주 좋은 방법인 것 같아요!

2023-08-05 02:43 UTC, merged