feat: 앱 생성 및 모델 생성, 회원가입 기본 세팅
QRTaxi/QRTaxi_Server pull request #2
Opened 2023-07-29 11:03 UTC by ChoiYoo

### 작업한 내용
- 앱 생성
   - driver (택시 기사 계정)
   - mypage (택시 기사 마이페이지) 
   - qr (큐알 관련)
   - call (배정 관련)
   - report (신고 관련) 
- drvier, qr, call, report 모델 생성
- 회원가입 기본 세팅
- base.py에 jwt 관련 기본세팅
### 논의할 내용
- erd를 바탕으로 모델 생성했는데, 모델 관련해서 보완해야 할 점 있으면 말해주세요!! (필드 등등)

### 추후 진행할 내용
- 회원가입 진행

2023-07-29 12:37 UTC, leehjhjhj requested changes
시간도 별로 없었는데.. 정말 수고 많으셨습니다~!~!
모델에 대한 저의 코멘트만 잠깐 봐주시면 될 것 같아용👍👍

2023-07-29 12:37 UTC, leehjhjhj commented on call/models/assign.py
> +    status = models.CharField(default="배정중", max_length=10)
여기에 chioces 있어야 될 것 같아요!
```python
status_choices = (
        ('waiting', '배정중'),
        ('success', '배정완료'),
        ('riding', '탑승완료'),
        ('finish', '운행종료'),
        ('cancel', '취소'),
    )
```
이거하고 choices=status_choices 이렇게 추가하면 더 쉬운 상태관리가 될 것 같아용

2023-07-29 12:37 UTC, leehjhjhj commented on driver/models/time.py
> +class TimestampedModel(models.Model):
택시기사에 대해서 fk가 없어요!! 의도 된 걸까요

2023-07-29 12:37 UTC, leehjhjhj commented on hackathon/settings/base.py
> +DJANGO_APPS = [
와우 이렇게 나누니깐 훨씬 깔끔한 것 같아요👍👍

2023-07-29 12:37 UTC, leehjhjhj commented on qr/models/qr.py
> +    map_image = models.ImageField(verbose_name="장소 이미지")
장소 이미지 아마 S3 버킷 url로 들어갈 것 같아서 그냥 charfield로 하는게 더 좋을 것 같아요!
대신 길이는 엄청 길게.. ex)256 ...

2023-07-29 12:37 UTC, leehjhjhj commented on qr/models/qr_image.py
> +    qr_image = models.ImageField()
이것도 마찬가지로 charfield로 부탁드립니당

2023-07-29 12:37 UTC, leehjhjhj commented on qr/models/qr_image.py
> +    qr_url = models.URLField(max_length=1024)
url 필드 모델 짤 때,URLField로 하는게 더 좋나요?? 저는 charfield로 해왔어서..

2023-07-29 12:40 UTC, ChoiYoo commented on call/models/assign.py
> +    status = models.CharField(default="배정중", max_length=10)
네넵! 예시까지..!! 감사합니당

2023-07-29 13:20 UTC, ChoiYoo commented on driver/models/time.py
> +class TimestampedModel(models.Model):
맞다..! 여쭤볼게 있었는데 생각해보니가 AbstractUser에 계정생성일이 있더라구요,,? 그래서 탈퇴일만 있으면 되는데, 저희 탈퇴했을 때, 유저를 삭제하는게 아니라면 driver에 탈퇴에 대한 불린값이 있어야 할 거 같아요,,,! 

이 부분에 대해서 정해진 다음에 모델 생성하려고 지금은 timestampedModel을 driver이 상속받는 형식으로 했습니다!

2023-07-29 13:20 UTC, ChoiYoo commented on qr/models/qr.py
> +    map_image = models.ImageField(verbose_name="장소 이미지")
오!! 알겠습니당!!

2023-07-29 13:23 UTC, ChoiYoo commented on qr/models/qr_image.py
> +    qr_url = models.URLField(max_length=1024)
이렇게 하면 자동으로 url 주소 형식에 대해서 체크를 해준다고 하더라구요..? 그래서 urlfield로 설정해놨는데 혹시 charfield가 더 편하시다면 말씀해주세용!! url 형식이 제대로 되었는지 확인이 따로 필요하지 않다면 charfield로 해도 될거 같아요!

2023-07-29 15:09 UTC, leehjhjhj commented on qr/models/qr_image.py
> +    qr_url = models.URLField(max_length=1024)
옹 그러면 그게 좋겠네요! 나중에 이상하면 그냥 charfield로 고고합시당

2023-07-29 15:12 UTC, leehjhjhj commented on driver/models/time.py
> +class TimestampedModel(models.Model):
아하 상속이 있었군요!! 못 봤었네요😂 맞아요 생각해보니깐 created_at은 이미 있으니깐 withdraw하고 update만 있으면 좋을 것 같아요. 그 삭제하는 것도 제가 알기론 그냥 is_active 인가? 자동으로 생성 되는거 있어서 그거 false로 해두면 로그인 못해서 그거 사용하면 될 것 같아요

2023-07-29 15:14 UTC, ChoiYoo commented on driver/models/time.py
> +class TimestampedModel(models.Model):
오홍 그렇군요..!! 그러면 created_at만 삭제해서 다시 푸쉬하겠습니다!!

2023-07-29 15:16 UTC, leehjhjhj commented on driver/models/time.py
> +class TimestampedModel(models.Model):
넵!!!

2023-07-30 01:01 UTC, kimjeongsoo20190147 commented
확인했습니다!! 짧은 시간 안에 쉽지 않았을텐데 고생했어요!!!...

2023-07-30 03:13 UTC, closed without merging